title: coder-dojo-training-test
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Readiness checklist
  - title: Potential barriers and tips to overcome them
  - title: 5 steps of succession and plan types
  - title: Useful resources
